# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
def pods_default
    pod 'Alamofire', '~> 4.6'
    pod 'RxSwift',    '~> 4.0'
    pod 'RxCocoa',    '~> 4.0'
    pod 'SDWebImage', '~> 4.0'
    pod 'Moya-ModelMapper/RxSwift'
    pod 'Moya/RxSwift'

    pod 'RxOptional'
end

target 'voxfeed' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pods_default
    
  target 'voxfeedTests' do
      inherit! :search_paths

       pods_default # Pods for testing
  end

  target 'voxfeedUITests' do
      inherit! :search_paths

    # Pods for testing
    pods_default
  end

end
