# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'voxfeed' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 4.6'
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'Skeleton'
  pod 'SDWebImage', '~> 4.0'

  target 'voxfeedTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'voxfeedUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
